learning_rate: 2e-05
warmup_steps: 25
random_seed: 42
node_rank: 0
nnodes: 1
rdzv_id: 123
rdzv_endpoint: 127.0.0.1:12222
deepspeed_cpu_offload_optimizer_ratio: 1
deepspeed_cpu_offload_optimizer_pin_memory: false
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
use_dolomite: false
